version: '2'
services:
  api:
    image: nexus.esolutions.ro/peon/api:latest
    stdin_open: true
    tty: true
    labels:
      traefik.frontend.rule: 'Host: peon.dev.esolutions.ro'
      traefik.port: '5000'
      traefik.enable: 'true'
      io.rancher.container.pull_image: always
  ui:
    image: nexus.esolutions.ro/peon/ui:latest
    stdin_open: true
    tty: true
    labels:
      traefik.frontend.rule: 'Host: peon.dev.esolutions.ro'
      traefik.port: '80'
      traefik.enable: 'true'
      traefik.frontend.redirect.entryPoint: https
      io.rancher.container.pull_image: always